global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'internal-healthcheck' # node exporter
    scrape_interval: 15s
    honor_labels: true
    static_configs:
    - targets:
       - localhost:9108

  - job_name: 'ext_https' # blackbox exporter
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://example.org    # Target to probe with https.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: example:9115

